# Generated by Django 5.2.3 on 2025-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='tracking_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
