# Generated by Django 5.2.3 on 2025-07-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tracking_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='item',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tracking',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
